import test from 'node:test';import assert from 'node:assert/strict';
import {parseFeed,eventHeat,buildEvents,buildDigests,enrichItem,canonicalURL,sameEvent,actorMatches} from '../src/intelligence.mjs';
const now=Date.parse('2026-10-08T10:00:00Z'),actors=[{id:'test',name:'Test Games',aliases:['Test Games'],tags:['IAA']}];
function item(title='Test Games launches puzzle 2',overrides={}){return enrichItem({title,url:'https://a.example/story',summary:'release of a new puzzle game',source:'A',origin:'discovery',publishedAt:new Date(now).toISOString(),discoveredAt:new Date(now).toISOString(),...overrides},actors,now)}
test('repeat collection never increases heat; source dates define 48h window',()=>{const a=item(),b=item(a.title,{url:'https://a.example/another'});assert.deepEqual(eventHeat([a,b],now),{heat:1,participants:1});assert.equal(eventHeat([item(a.title,{publishedAt:new Date(now-24*3600000).toISOString()})],now).heat,.5);assert.equal(eventHeat([item(a.title,{publishedAt:new Date(now-49*3600000).toISOString()})],now).participants,0);assert.equal(eventHeat([item(a.title,{publishedAt:null})],now).heat,0)});
test('RSS/Atom preserve source date; future/unknown dates do not become today',()=>{const src={id:'rss',name:'Test Games',kind:'official',actorId:'test'},rss='<rss><channel><item><title>Launch</title><link>https://a.example/s</link><pubDate>Thu, 08 Oct 2026 09:00:00 GMT</pubDate></item></channel></rss>';assert.equal(parseFeed(rss,src,now)[0].publishedAt,'2026-10-08T09:00:00.000Z');const atom='<feed><entry><title>Launch</title><link rel="alternate" href="https://a.example/atom"/><published>2026-10-09T00:00:00Z</published></entry></feed>';assert.equal(parseFeed(atom,src,now)[0].publishedAt,null);assert.throws(()=>parseFeed('<html>blocked</html>',src,now));assert.equal(enrichItem({...item(),publishedAt:null},actors,now).archived,true)});
test('clustering requires matching substance, not merely same company; publisher duplicates count once',()=>{const a=item(),b=item(a.title+' - Other Publisher',{url:'https://b.example/s',source:'B'});assert.equal(buildEvents([a,b],now).length,1);assert.equal(buildEvents([a,b],now)[0].participants,2);assert.equal(sameEvent(a,item('Test Games launches puzzle 3')),false);assert.equal(sameEvent(a,item('Test Games lays off employees')),false);assert.equal(actorMatches('United teams play games',{aliases:['Unity']}),false)});
test('daily edition retains 09:00 boundary and is immutable after publication',()=>{const before=item('Test Games launches puzzle 2',{publishedAt:'2026-10-08T00:45:00Z'}),after=item('Test Games launches puzzle 3',{publishedAt:'2026-10-08T01:15:00Z',url:'https://b.example/after'});const editions=buildDigests(buildEvents([before,after],now),[],now);assert.equal(editions[0].windowEnd,'2026-10-08T01:00:00.000Z');assert.equal(editions[0].entries.length,1);assert.equal(editions[0].entries[0].title,before.title);assert.deepEqual(buildDigests([],editions,now),editions)});
test('tracking URL parameters deduplicate and unsafe URLs reject',()=>{assert.equal(canonicalURL('https://a.example/s?utm_source=x#fragment'),'https://a.example/s');assert.equal(canonicalURL('javascript:alert(1)'),null)});
test('an official feed and its Google News copy count as one publisher',()=>{const official=item('Test Games launches puzzle 2',{origin:'official',ownerActorId:'test'}),copy=item(official.title,{url:'https://news.google.com/rss/articles/example',publisherUrl:'https://a.example/',source:'A via Google'});assert.equal(eventHeat([official,copy],now).participants,1)});
test('a bare product/forum title is retained as discovery but excluded from events',()=>{const x=item('剑意（微信小游戏）',{summary:'剑意（微信小游戏） 虎扑体育',source:'虎扑体育'});assert.equal(x.materialReady,false);assert.equal(buildEvents([x],now).length,0)});
