import {readFile,writeFile,mkdir,cp} from 'node:fs/promises';
await mkdir('public/data',{recursive:true});
let html=await readFile('src/page.html','utf8');html=html.replace('href="/"','href="./"').replace('src="/app.js"','src="./app.js"').replace('私人游戏情报站 · v2','公开游戏情报站 · 云端快照');
let js=await readFile('src/ui.js','utf8');const start=js.indexOf('async function api('),end=js.indexOf('function dateMatches(',start);if(start<0||end<0)throw new Error('API adapter marker missing');
const adapter=await readFile('src/static-api.js','utf8');js=js.slice(0,start)+adapter+'\n'+js.slice(end);
js=js.replaceAll('保存至私人研究库','保存到当前浏览器').replaceAll('云端保存，刷新可读取','本地保存，不上传或共享给同事').replaceAll('已保存至私人研究库','已保存到当前浏览器');
js=js.replace("'↻ 立即更新'","'↻ 同步最新快照'").replace('重试该源','同步快照').replace('单独更新','同步快照').replace('正在逐项采集，最长约一分多钟；失败会保留上次数据','正在读取云端最近成功快照，后台采集约每小时运行');
js=js.replace("'公开游戏情报站 · v2.2'","'公开游戏情报站 · 云端快照'");
js=js.replace("['最近更新成功来源'","['榜单与基础资讯来源'");
js=js.replace("data.auth?.audience==='public'","(data.auth?.audience||'public')==='public'");
const radar=await readFile('src/radar-ui.js','utf8');js=js.replace('function toast(s){',radar+'\nfunction toast(s){');
js=js.replace("a=a.filter(x=>x.tags?.some(t=>", "a=a.filter(x=>(x.ruleScore===undefined||(!x.noise&&x.ruleScore>=40))&&(x.tags?.some(t=>");
js=js.replace("test(x.title));if(topic", "test(x.title)));if(topic");
js=js.replace("['selected','all','reward','summary','saved'].includes(view)","['selected','all','reward','summary','saved','actors','events'].includes(view)");
js=js.replace("if(view==='charts')$('content').innerHTML=chartsHTML();", "if(view==='actors')$('content').innerHTML=actorsHTML();else if(view==='events')$('content').innerHTML=topicBar+eventsHTML();else if(view==='digest')$('content').innerHTML=digestHTML();else if(view==='charts')$('content').innerHTML=chartsHTML();");
js=js.replace("$('content').innerHTML=sourcesHTML()", "$('content').innerHTML=sourcesHTML()+intelligenceSourcesHTML()");
js=js.replace("$('content').innerHTML=topicBar+(view==='selected'?", "$('content').innerHTML=(view==='selected'?radarTeaser():'')+topicBar+(view==='selected'?");
js=js.replace("if($('chartSelect'))", "setupRadarControls();if($('chartSelect'))");
js=js.replace("const slots=Object.values(data.charts)", "if(['actors','events','digest'].includes(view))$('heading').textContent=names[view];const slots=Object.values(data.charts)");
js=js.replace("{view,games:matchingGames", "{view,actors:intel().actors.filter(a=>(actorCategory==='全部'||a.category===actorCategory)&&(actorPick==='all'||a.id===actorPick)&&(!followOnly||followed.includes(a.id))&&(!query||(a.name+' '+a.focus).toLowerCase().includes(query.toLowerCase()))),events:intel().events.filter(intelMatch).filter(x=>!hotOnly||x.participants>=2),digest:filteredDigest(),games:matchingGames");
html=html.replace('↻ 立即更新','↻ 同步最新快照');
html=html.replace('</head>','<link rel="alternate" type="application/rss+xml" title="Game Hot 行动者动态" href="./feed.xml"></head>');html=html.replace('结构参考 AI Hot ↗</a>','结构参考 AI Hot ↗</a><a href="./feed.xml" target="_blank" rel="noopener" style="display:block;margin-top:7px">订阅动态 RSS ↗</a>');
await writeFile('public/index.html',html);await writeFile('public/app.js',(await readFile('src/export-utils.mjs','utf8')).replace(/^export /gm,'')+'\n'+js);await cp('data','public/data',{recursive:true});await writeFile('public/.nojekyll','');
const snapshot=JSON.parse(await readFile('data/snapshot.json','utf8')),xml=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));const items=(snapshot.intelligence?.events||[]).filter(e=>e.publishedAt).sort((a,b)=>Date.parse(b.publishedAt)-Date.parse(a.publishedAt)).slice(0,40);
await writeFile('public/feed.xml','<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Game Hot 行动者动态</title><link>https://creepergreg4-tech.github.io/game-hot/</link><description>原文标题与摘录；规则归组候选，事实与效果需回看来源。</description>'+items.map(e=>'<item><title>'+xml(e.title)+'</title><link>'+xml(e.url)+'</link><guid isPermaLink="false">gamehot:'+xml(e.id)+'</guid><pubDate>'+new Date(e.publishedAt).toUTCString()+'</pubDate><description>'+xml(e.summary)+' · '+xml(e.verification)+'</description></item>').join('')+'</channel></rss>');console.log('Static build ready');
